In [59]:
#Importacion de librerias
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
bill = pd.read_csv('billboard2.csv', sep=';',encoding='latin',parse_dates=['date.entered','date.peaked'],infer_datetime_format=True)

In [61]:
bill.head(10)

,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,81,54.0,44.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
for c in bill.columns:
    print ("---- %s ---" % c)
    print (bill[c].value_counts())

---- artist.inverted ---
Jay-Z                    5
Dixie Chicks, The        4
Houston, Whitney         4
Spears, Britney          3
SheDaisy                 3
N'Sync                   3
Jackson, Alan            3
McGraw, Tim              3
Price, Kelly             3
Sisqo                    3
Backstreet Boys, The     3
Braxton, Toni            3
Lonestar                 3
Eminem                   3
Aguilera, Christina      3
DMX                      3
Destiny's Child          3
Thomas, Carl             3
Rimes, LeAnn             3
Limp Bizkit              3
Martin, Ricky            3
Vitamin C                2
Iglesias, Enrique        2
Eve                      2
3 Doors Down             2
Simpson, Jessica         2
Red Hot Chili Peppers    2
Strait, George           2
M2M                      2
Anthony, Marc            2
                        ..
SoulDecision             1
Barenaked Ladies         1
Raye, Collin             1
Williams, Robbie         1
Sonique                  1
McKnight, Brian          1
J-Shin                   1
Estefan, Gloria          1
Fabian, Lara             1
Filter                   1
Bega, Lou                1
Drama                    1
2 Pac                    1
Heatherly, Eric          1
Sammie                   1
Jones, Donell            1
Moore, Mandy             1
Profyle                  1
Master P                 1
Son By Four              1
Clark, Terri             1
Wills, Mark              1
Lil Wayne                1
Mumba, Samantha          1
Kravitz, Lenny           1
504 Boyz                 1
Hoku                     1
Tuesday                  1
Cyrus, Billy Ray         1
Kelis                    1
Name: artist.inverted, Length: 228, dtype: int64
---- track ---
Where I Wanna Be                2
None Of Ur Friends Business     1
The Best Man I Can Be           1
Bent                            1
Some Things Never Change        1
Back At One                     1
One Voice                       1
That's The Way It Is            1
You Won't Be Lonely Now         1
Let's Make Love                 1
Learn To Fly                    1
Shackles (Praise You)           1
Dear Lie                        1
Doesn't Really Matter           1
I Don't Wanna                   1
Smoke Rings In The Dark         1
Whistle While You Twurk         1
Thank God I Found You           1
The Best Day                    1
With Arms Wide Open             1
You're A God                    1
Meanwhile Back At The Ranch     1
The Best Of Me                  1
Souljas                         1
3 Little Words                  1
Wifey                           1
Left, Right, Left               1
We Danced                       1
Prayin' For Daylight            1
There You Are                   1
                               ..
Girls Dem Sugar                 1
Shake Ya Ass                    1
Deep Inside Of You              1
Hey Papi                        1
No More Rain (In This Cloud)    1
Daddy Won't Sell The Farm       1
My First Love                   1
I Think I'm In Love With You    1
A Little Gasoline               1
Mirror Mirror                   1
The Little Girl                 1
U Understand                    1
That's What I'm Looking For     1
Lucky                           1
Original Prankster              1
Still In My Heart               1
Liar                            1
The Chain Of Love               1
Party Up (Up In Here)           1
Deep Inside                     1
Another Dumb Blonde             1
Smile                           1
Goodbye Earl                    1
Bring It All To Me              1
Rhythm Divine                   1
Cowboy Take Me Away             1
Tha Block Is Hot                1
All The Small Things            1
Do You                          1
Back Here                       1
Name: track, Length: 316, dtype: int64
---- time ---
3:50    9
3:54    7
3:55    7
4:06    6
4:02    6
3:46    6
3:52    6
3:30    6
4:12    6
3:45    6
4:17    6
3:51    6
4:00    6
3:19    5
3:48    5
4:23    5
3:56    5
4:07    5
3:23    5
4:10    5
4:18    5
4:16    5
3:44    4
3:43    4
4:05    4
4:30    4
3:40    4
4:13    4
4:04    4
3:36    3
       ..
3:07    1
3:20    1
7:50    1
4:43    1
4:27    1
4:45    1
3:05    1
4:46    1
2:36    1
5:12    1
5:21    1
3:39    1
5:28    1
4:33    1
7:35    1
6:22    1
6:20    1
5:10    1
4:21    1
5:16    1
3:49    1
5:43    1
3:53    1
5:19    1
6:17    1
5:33    1
7:10    1
4:32    1
4:40    1
3:03    1
Name: time, Length: 126, dtype: int64
---- genre ---
Rock           137
Country         74
Rap             58
R&B             23
Pop              9
Latin            9
Electronica      4
Jazz             1
Gospel           1
Reggae           1
Name: genre, dtype: int64
---- date.entered ---
2000-01-29    11
2000-08-12    10
2000-03-18     9
2000-02-19     9
2000-05-13     9
1999-12-04     8
2000-03-04     8
2000-02-12     7
2000-04-01     7
2000-08-05     7
2000-01-22     7
2000-09-09     7
2000-06-17     7
2000-04-29     7
2000-06-24     7
2000-03-25     7
2000-04-15     7
2000-04-22     7
1999-11-27     6
2000-02-26     6
2000-07-15     6
2000-08-19     6
1999-12-25     6
2000-08-26     6
2000-06-10     6
2000-10-21     6
2000-07-08     5
2000-09-30     5
2000-07-01     5
2000-04-08     5
              ..
2000-01-15     4
2000-01-01     4
2000-09-23     4
1999-11-13     4
1999-11-20     4
2000-10-14     4
1999-10-23     3
2000-05-20     3
2000-03-11     3
2000-11-25     3
2000-12-02     3
2000-10-07     3
2000-02-05     3
2000-11-11     3
2000-01-08     3
1999-10-30     2
2000-06-03     2
1999-12-18     2
1999-10-16     2
1999-11-06     2
2000-11-18     2
1999-10-09     2
2000-07-22     1
1999-06-05     1
2000-12-16     1
1999-07-17     1
2000-12-23     1
1999-09-04     1
1999-09-11     1
2000-12-30     1
Name: date.entered, Length: 68, dtype: int64
---- date.peaked ---
2000-12-02    17
2000-01-22    14
2000-04-15    12
2000-09-16    11
2000-01-08    10
2000-01-29     9
2000-02-12     9
2000-08-12     9
2000-07-01     8
2000-06-17     8
2000-05-06     8
2000-04-08     8
2000-11-18     8
2000-10-28     8
2000-07-29     8
2000-05-20     7
2000-12-16     7
2000-09-02     7
2000-03-11     7
2000-08-05     7
2000-03-04     7
2000-12-30     6
2000-09-09     6
2000-06-10     6
2000-02-19     6
2000-03-25     6
2000-08-19     6
2000-03-18     6
2000-04-22     6
2000-06-24     5
2000-09-30     5
2000-10-21     5
2000-07-22     5
2000-10-07     5
2000-01-01     4
2000-10-14     4
2000-05-13     4
2000-08-26     4
2000-02-05     4
2000-12-23     4
2000-02-26     3
2000-11-11     3
2000-11-25     3
2000-12-09     3
2000-01-15     3
2000-07-08     3
2000-05-27     3
2000-06-03     2
2000-07-15     2
2000-04-01     2
2000-04-29     2
2000-09-23     1
2000-11-04     1
Name: date.peaked, dtype: int64
---- x1st.week ---
77     16
99     14
98     14
81     14
75     12
79     12
80     11
85     11
97     10
74     10
86     10
82      9
71      9
94      9
76      9
78      8
84      8
87      8
89      8
95      8
83      7
96      7
91      6
92      6
63      6
73      6
72      5
70      5
100     5
68      4
       ..
93      3
88      2
59      2
57      2
58      2
50      2
64      2
65      2
61      1
43      1
22      1
25      1
28      1
36      1
38      1
39      1
40      1
41      1
42      1
46      1
60      1
48      1
49      1
66      1
51      1
52      1
54      1
56      1
62      1
15      1
Name: x1st.week, Length: 63, dtype: int64
---- x2nd.week ---
76.0     12
72.0     12
68.0     11
67.0     10
83.0     10
71.0      9
74.0      9
73.0      8
75.0      8
77.0      8
66.0      8
70.0      8
99.0      7
78.0      7
88.0      7
86.0      7
98.0      6
64.0      6
97.0      6
80.0      6
84.0      6
55.0      6
62.0      5
59.0      5
52.0      5
92.0      5
69.0      5
61.0      5
32.0      5
63.0      5
         ..
100.0     3
29.0      3
96.0      3
54.0      2
51.0      2
45.0      2
93.0      2
47.0      2
48.0      2
39.0      2
90.0      2
56.0      2
34.0      2
35.0      2
38.0      2
49.0      1
20.0      1
37.0      1
21.0      1
31.0      1
50.0      1
41.0      1
15.0      1
22.0      1
25.0      1
40.0      1
23.0      1
57.0      1
8.0       1
28.0      1
Name: x2nd.week, Length: 72, dtype: int64
---- x3rd.week ---
65.0     11
66.0     10
72.0      9
69.0      9
75.0      8
62.0      8
71.0      8
51.0      7
63.0      7
68.0      7
70.0      7
81.0      6
53.0      6
76.0      6
97.0      6
52.0      6
59.0      5
57.0      5
54.0      5
80.0      5
79.0      5
67.0      5
96.0      5
98.0      5
61.0      5
88.0      5
74.0      5
92.0      5
64.0      5
55.0      4
         ..
100.0     3
90.0      3
77.0      3
89.0      3
28.0      2
91.0      2
34.0      2
84.0      2
87.0      2
86.0      2
29.0      2
95.0      2
46.0      2
47.0      2
20.0      2
58.0      2
82.0      2
39.0      2
38.0      1
21.0      1
17.0      1
13.0      1
26.0      1
7.0       1
78.0      1
16.0      1
18.0      1
42.0      1
6.0       1
12.0      1
Name: x3rd.week, Length: 79, dtype: int64
---- x4th.week ---
52.0    9
61.0    8
73.0    8
67.0    7
69.0    7
63.0    7
54.0    7
64.0    7
59.0    7
39.0    6
70.0    6
76.0    6
62.0    6
55.0    5
58.0    5
56.0    5
72.0    5
80.0    5
65.0    5
87.0    5
26.0    5
91.0    5
71.0    5
45.0    4
17.0    4
46.0    4
36.0    4
79.0    4
40.0    4
42.0    4
       ..
28.0    2
98.0    2
14.0    2
38.0    2
85.0    2
75.0    2
93.0    2
33.0    2
5.0     1
18.0    1
31.0    1
30.0    1
97.0    1
47.0    1
34.0    1
88.0    1
81.0    1
86.0    1
83.0    1
68.0    1
35.0    1
48.0    1
9.0     1
44.0    1
21.0    1
19.0    1
8.0     1
11.0    1
25.0    1
22.0    1
Name: x4th.week, Length: 88, dtype: int64
---- x5th.week ---
67.0     8
59.0     7
66.0     7
57.0     6
54.0     6
60.0     6
51.0     6
63.0     6
65.0     6
55.0     6
46.0     6
38.0     6
23.0     5
86.0     5
69.0     5
62.0     5
100.0    5
83.0     5
48.0     5
91.0     5
45.0     5
84.0     5
39.0     4
56.0     4
82.0     4
34.0     4
11.0     4
26.0     4
53.0     4
70.0     4
        ..
78.0     2
97.0     2
21.0     2
47.0     2
89.0     2
30.0     2
25.0     2
95.0     2
76.0     2
64.0     2
72.0     2
15.0     2
12.0     2
44.0     2
58.0     2
28.0     2
18.0     1
80.0     1
29.0     1
31.0     1
19.0     1
90.0     1
32.0     1
22.0     1
88.0     1
79.0     1
7.0      1
24.0     1
43.0     1
14.0     1
Name: x5th.week, Length: 91, dtype: int64
---- x6th.week ---
83.0    8
48.0    7
57.0    7
64.0    7
37.0    7
52.0    6
44.0    6
42.0    6
31.0    6
73.0    6
79.0    5
60.0    5
54.0    5
47.0    5
49.0    5
88.0    5
77.0    5
40.0    5
33.0    5
25.0    5
19.0    5
56.0    4
63.0    4
7.0     4
41.0    4
69.0    4
34.0    4
99.0    4
46.0    4
13.0    4
       ..
45.0    2
91.0    2
53.0    2
32.0    2
95.0    2
90.0    2
80.0    2
29.0    2
39.0    2
71.0    2
97.0    1
85.0    1
89.0    1
72.0    1
1.0     1
86.0    1
3.0     1
75.0    1
26.0    1
84.0    1
24.0    1
9.0     1
61.0    1
36.0    1
6.0     1
92.0    1
11.0    1
28.0    1
17.0    1
98.0    1
Name: x6th.week, Length: 92, dtype: int64
---- x7th.week ---
61.0    7
36.0    7
44.0    6
47.0    6
56.0    6
30.0    6
20.0    5
33.0    5
52.0    5
34.0    5
54.0    5
65.0    5
40.0    5
82.0    5
48.0    5
26.0    5
60.0    5
35.0    5
43.0    4
39.0    4
41.0    4
76.0    4
32.0    4
24.0    4
28.0    4
74.0    4
15.0    4
59.0    4
7.0     4
92.0    4
       ..
14.0    2
38.0    2
51.0    2
93.0    2
49.0    2
86.0    2
67.0    2
78.0    2
75.0    2
95.0    2
68.0    2
42.0    2
45.0    2
83.0    2
11.0    2
96.0    1
1.0     1
10.0    1
97.0    1
3.0     1
8.0     1
5.0     1
90.0    1
77.0    1
19.0    1
69.0    1
13.0    1
79.0    1
98.0    1
94.0    1
Name: x7th.week, Length: 90, dtype: int64
---- x8th.week ---
58.0    10
32.0     7
46.0     6
16.0     6
29.0     6
60.0     5
39.0     5
48.0     5
47.0     5
28.0     5
35.0     4
45.0     4
27.0     4
31.0     4
33.0     4
57.0     4
55.0     4
21.0     4
80.0     4
86.0     4
81.0     4
51.0     4
90.0     4
10.0     4
9.0      4
38.0     3
52.0     3
24.0     3
97.0     3
96.0     3
        ..
93.0     2
88.0     2
84.0     2
89.0     2
66.0     2
56.0     2
73.0     2
74.0     2
95.0     2
41.0     2
34.0     2
42.0     2
79.0     2
4.0      1
65.0     1
99.0     1
49.0     1
25.0     1
8.0      1
70.0     1
77.0     1
54.0     1
71.0     1
62.0     1
61.0     1
68.0     1
15.0     1
63.0     1
17.0     1
91.0     1
Name: x8th.week, Length: 91, dtype: int64
---- x9th.week ---
38.0    8
22.0    6
28.0    6
51.0    6
26.0    6
36.0    5
95.0    5
32.0    5
45.0    5
54.0    5
82.0    5
90.0    5
1.0     5
17.0    4
27.0    4
14.0    4
42.0    4
40.0    4
61.0    4
55.0    4
24.0    4
60.0    4
44.0    4
12.0    4
78.0    4
7.0     4
34.0    4
9.0     4
49.0    3
53.0    3
       ..
41.0    2
88.0    2
35.0    2
98.0    2
31.0    2
74.0    2
66.0    2
81.0    2
77.0    1
96.0    1
64.0    1
72.0    1
16.0    1
70.0    1
67.0    1
75.0    1
4.0     1
71.0    1
83.0    1
86.0    1
2.0     1
84.0    1
3.0     1
93.0    1
11.0    1
6.0     1
48.0    1
46.0    1
20.0    1
99.0    1
Name: x9th.week, Length: 92, dtype: int64
---- x10th.week ---
25.0    8
34.0    8
92.0    7
27.0    7
38.0    6
54.0    5
61.0    5
35.0    5
29.0    5
55.0    5
40.0    5
19.0    4
5.0     4
57.0    4
2.0     4
79.0    4
9.0     4
26.0    4
24.0    4
18.0    4
97.0    4
46.0    4
7.0     4
69.0    4
85.0    3
32.0    3
59.0    3
56.0    3
31.0    3
70.0    3
       ..
48.0    2
39.0    2
84.0    2
80.0    2
77.0    2
76.0    1
71.0    1
74.0    1
91.0    1
87.0    1
95.0    1
93.0    1
98.0    1
23.0    1
65.0    1
63.0    1
64.0    1
53.0    1
49.0    1
45.0    1
20.0    1
16.0    1
33.0    1
37.0    1
73.0    1
41.0    1
81.0    1
22.0    1
60.0    1
88.0    1
Name: x10th.week, Length: 92, dtype: int64
---- x11th.week ---
8.0      6
22.0     6
1.0      5
37.0     5
63.0     5
17.0     5
26.0     5
13.0     5
43.0     5
44.0     5
52.0     4
29.0     4
96.0     4
54.0     4
27.0     4
91.0     4
36.0     4
7.0      4
11.0     4
95.0     4
5.0      4
53.0     4
33.0     3
85.0     3
100.0    3
23.0     3
32.0     3
64.0     3
35.0     3
28.0     3
        ..
83.0     2
40.0     2
48.0     2
73.0     2
67.0     2
76.0     2
82.0     1
70.0     1
99.0     1
77.0     1
90.0     1
45.0     1
78.0     1
58.0     1
46.0     1
93.0     1
15.0     1
66.0     1
39.0     1
56.0     1
94.0     1
25.0     1
62.0     1
59.0     1
55.0     1
41.0     1
69.0     1
65.0     1
86.0     1
89.0     1
Name: x11th.week, Length: 92, dtype: int64
---- x12th.week ---
6.0      6
15.0     6
8.0      6
31.0     5
43.0     5
56.0     5
27.0     5
46.0     4
53.0     4
28.0     4
29.0     4
45.0     4
82.0     4
25.0     4
51.0     4
13.0     4
4.0      4
89.0     4
1.0      4
26.0     3
72.0     3
33.0     3
88.0     3
70.0     3
37.0     3
42.0     3
19.0     3
11.0     3
98.0     3
59.0     3
        ..
100.0    2
40.0     2
67.0     2
50.0     2
62.0     2
39.0     2
96.0     1
79.0     1
47.0     1
75.0     1
10.0     1
66.0     1
54.0     1
74.0     1
76.0     1
81.0     1
68.0     1
34.0     1
17.0     1
12.0     1
86.0     1
64.0     1
16.0     1
63.0     1
18.0     1
48.0     1
94.0     1
44.0     1
73.0     1
77.0     1
Name: x12th.week, Length: 91, dtype: int64
---- x13th.week ---
1.0      8
6.0      6
46.0     5
11.0     5
43.0     4
85.0     4
53.0     4
23.0     4
70.0     4
19.0     4
5.0      4
36.0     4
88.0     4
79.0     4
27.0     4
40.0     3
68.0     3
57.0     3
96.0     3
26.0     3
33.0     3
29.0     3
55.0     3
15.0     3
35.0     3
10.0     3
61.0     3
28.0     3
93.0     3
21.0     3
        ..
84.0     2
31.0     2
47.0     2
38.0     2
65.0     2
90.0     2
60.0     2
32.0     2
69.0     2
2.0      1
8.0      1
91.0     1
18.0     1
20.0     1
99.0     1
74.0     1
100.0    1
92.0     1
71.0     1
77.0     1
59.0     1
58.0     1
64.0     1
45.0     1
66.0     1
80.0     1
48.0     1
78.0     1
24.0     1
51.0     1
Name: x13th.week, Length: 86, dtype: int64
---- x14th.week ---
1.0      7
24.0     6
91.0     6
28.0     5
2.0      5
44.0     5
20.0     5
53.0     5
66.0     5
6.0      4
13.0     4
60.0     4
88.0     4
5.0      4
32.0     4
33.0     4
4.0      4
8.0      3
93.0     3
36.0     3
96.0     3
12.0     3
78.0     3
21.0     3
86.0     3
15.0     3
29.0     3
57.0     3
61.0     3
85.0     3
        ..
18.0     1
7.0      1
30.0     1
26.0     1
84.0     1
11.0     1
35.0     1
52.0     1
89.0     1
82.0     1
40.0     1
41.0     1
51.0     1
92.0     1
50.0     1
58.0     1
63.0     1
100.0    1
14.0     1
39.0     1
43.0     1
38.0     1
75.0     1
48.0     1
46.0     1
23.0     1
72.0     1
76.0     1
17.0     1
98.0     1
Name: x14th.week, Length: 87, dtype: int64
---- x15th.week ---
100.0    6
1.0      5
57.0     5
62.0     5
89.0     5
27.0     4
18.0     4
99.0     4
32.0     4
38.0     4
2.0      4
93.0     4
17.0     3
61.0     3
73.0     3
34.0     3
4.0      3
52.0     3
3.0      3
21.0     3
44.0     3
15.0     3
19.0     3
60.0     3
5.0      3
8.0      3
11.0     3
6.0      3
36.0     3
41.0     3
        ..
87.0     2
7.0      2
28.0     2
77.0     2
83.0     1
59.0     1
92.0     1
33.0     1
85.0     1
82.0     1
47.0     1
65.0     1
43.0     1
70.0     1
37.0     1
39.0     1
40.0     1
42.0     1
68.0     1
48.0     1
88.0     1
46.0     1
20.0     1
50.0     1
98.0     1
69.0     1
55.0     1
56.0     1
71.0     1
91.0     1
Name: x15th.week, Length: 86, dtype: int64
---- x16th.week ---
17.0    5
2.0     5
94.0    5
93.0    5
7.0     4
11.0    4
15.0    4
63.0    4
58.0    4
84.0    4
31.0    4
4.0     4
8.0     4
41.0    3
81.0    3
70.0    3
20.0    3
9.0     3
96.0    3
64.0    3
1.0     3
71.0    3
3.0     3
76.0    3
21.0    3
28.0    3
35.0    3
90.0    3
98.0    3
62.0    3
       ..
99.0    2
89.0    2
88.0    2
43.0    2
80.0    2
27.0    2
25.0    2
39.0    2
47.0    2
10.0    1
46.0    1
65.0    1
66.0    1
45.0    1
82.0    1
77.0    1
37.0    1
53.0    1
67.0    1
32.0    1
22.0    1
72.0    1
79.0    1
6.0     1
69.0    1
48.0    1
42.0    1
57.0    1
33.0    1
44.0    1
Name: x16th.week, Length: 78, dtype: int64
---- x17th.week ---
86.0     6
94.0     5
100.0    4
11.0     4
93.0     4
3.0      4
91.0     4
2.0      4
13.0     4
87.0     4
30.0     4
15.0     3
58.0     3
31.0     3
97.0     3
92.0     3
5.0      3
83.0     3
22.0     3
14.0     3
62.0     3
45.0     3
8.0      3
6.0      3
35.0     3
10.0     3
48.0     3
1.0      3
98.0     3
51.0     3
        ..
99.0     2
53.0     2
80.0     2
47.0     2
37.0     2
23.0     1
63.0     1
57.0     1
29.0     1
74.0     1
68.0     1
65.0     1
70.0     1
69.0     1
71.0     1
84.0     1
66.0     1
50.0     1
82.0     1
39.0     1
4.0      1
9.0      1
95.0     1
21.0     1
89.0     1
72.0     1
16.0     1
54.0     1
18.0     1
77.0     1
Name: x17th.week, Length: 79, dtype: int64
---- x18th.week ---
3.0      6
100.0    6
16.0     5
84.0     5
93.0     4
82.0     4
65.0     4
88.0     3
33.0     3
96.0     3
92.0     3
30.0     3
85.0     3
60.0     3
90.0     3
12.0     3
2.0      3
99.0     3
11.0     3
89.0     3
14.0     3
10.0     3
29.0     2
34.0     2
62.0     2
7.0      2
81.0     2
20.0     2
24.0     2
8.0      2
        ..
18.0     1
80.0     1
78.0     1
6.0      1
15.0     1
40.0     1
70.0     1
66.0     1
87.0     1
91.0     1
4.0      1
74.0     1
83.0     1
44.0     1
98.0     1
26.0     1
46.0     1
25.0     1
32.0     1
42.0     1
56.0     1
53.0     1
31.0     1
59.0     1
76.0     1
38.0     1
97.0     1
51.0     1
54.0     1
79.0     1
Name: x18th.week, Length: 83, dtype: int64
---- x19th.week ---
99.0    4
95.0    4
85.0    4
21.0    4
18.0    4
7.0     4
11.0    4
3.0     4
4.0     3
94.0    3
79.0    3
73.0    3
91.0    3
17.0    3
98.0    3
52.0    3
93.0    3
19.0    3
96.0    3
23.0    3
97.0    3
24.0    3
89.0    3
83.0    3
9.0     2
56.0    2
90.0    2
29.0    2
42.0    2

Name: x45th.week, dtype: int64
---- x46th.week ---
7.0     1
21.0    1
31.0    1
37.0    1
5.0     1
Name: x46th.week, dtype: int64
---- x47th.week ---
7.0     1
22.0    1
38.0    1
41.0    1
6.0     1
Name: x47th.week, dtype: int64
---- x48th.week ---
9.0     1
24.0    1
39.0    1
8.0     1
Name: x48th.week, dtype: int64
---- x49th.week ---
9.0     2
28.0    1
42.0    1
Name: x49th.week, dtype: int64
---- x50th.week ---
12.0    1
33.0    1
49.0    1
10.0    1
Name: x50th.week, dtype: int64
---- x51st.week ---
14.0    1
42.0    1
49.0    1
12.0    1
Name: x51st.week, dtype: int64
---- x52nd.week ---
16.0    1
42.0    1
48.0    1
15.0    1
Name: x52nd.week, dtype: int64
---- x53rd.week ---
17.0    1
49.0    1
47.0    1
20.0    1
Name: x53rd.week, dtype: int64
---- x54th.week ---
17.0    1
22.0    1
Name: x54th.week, dtype: int64
---- x55th.week ---
21.0    1
22.0    1
Name: x55th.week, dtype: int64
---- x56th.week ---
26.0    1
25.0    1
Name: x56th.week, dtype: int64
---- x57th.week ---
29.0    1
26.0    1
Name: x57th.week, dtype: int64
---- x58th.week ---
32.0    1
31.0    1
Name: x58th.week, dtype: int64
---- x59th.week ---
39.0    1
32.0    1
Name: x59th.week, dtype: int64
---- x60th.week ---
39.0    1
37.0    1
Name: x60th.week, dtype: int64
---- x61st.week ---
43.0    1
42.0    1
Name: x61st.week, dtype: int64
---- x62nd.week ---
47.0    1
42.0    1
Name: x62nd.week, dtype: int64
---- x63rd.week ---
50.0    1
45.0    1
Name: x63rd.week, dtype: int64
---- x64th.week ---
50.0    2
Name: x64th.week, dtype: int64
---- x65th.week ---
49.0    1
Name: x65th.week, dtype: int64
---- x66th.week ---
Series([], Name: x66th.week, dtype: int64)
---- x67th.week ---
Series([], Name: x67th.week, dtype: int64)
---- x68th.week ---
Series([], Name: x68th.week, dtype: int64)
---- x69th.week ---
Series([], Name: x69th.week, dtype: int64)
---- x70th.week ---
Series([], Name: x70th.week, dtype: int64)
---- x71st.week ---
Series([], Name: x71st.week, dtype: int64)
---- x72nd.week ---
Series([], Name: x72nd.week, dtype: int64)
---- x73rd.week ---
Series([], Name: x73rd.week, dtype: int64)
---- x74th.week ---
Series([], Name: x74th.week, dtype: int64)
---- x75th.week ---
Series([], Name: x75th.week, dtype: int64)
---- x76th.week ---
Series([], Name: x76th.week, dtype: int64)

In [5]:
help(bill.fillna)

Help on method fillna in module pandas.core.frame:

fillna(value=None, method=None, axis=None, inplace=False, limit=None, downcast=None, **kwargs) method of pandas.core.frame.DataFrame instance
    Fill NA/NaN values using the specified method

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame). (values not
        in the dict/Series/DataFrame will not be filled). This value cannot
        be a list.
    method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series
        pad / ffill: propagate last valid observation forward to next valid
        backfill / bfill: use NEXT valid observation to fill gap
    axis : {0 or 'index', 1 or 'columns'}
    inplace : boolean, default False
        If True, fill in place. Note: this will modify any
        other views on this object, (e.g. a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        If method is specified, this is the maximum number of consecutive
        NaN values to forward/backward fill. In other words, if there is
        a gap with more than this number of consecutive NaNs, it will only
        be partially filled. If method is not specified, this is the
        maximum number of entries along the entire axis where NaNs will be
        filled. Must be greater than 0 if not None.
    downcast : dict, default is None
        a dict of item->dtype of what to downcast if possible,
        or the string 'infer' which will try to downcast to an appropriate
        equal type (e.g. float64 to int64 if possible)

    See Also
    --------
    reindex, asfreq

    Returns
    -------
    filled : DataFrame

    Examples
    --------
    >>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
    ...                    [3, 4, np.nan, 1],
    ...                    [np.nan, np.nan, np.nan, 5],
    ...                    [np.nan, 3, np.nan, 4]],
    ...                    columns=list('ABCD'))
    >>> df
         A    B   C  D
    0  NaN  2.0 NaN  0
    1  3.0  4.0 NaN  1
    2  NaN  NaN NaN  5
    3  NaN  3.0 NaN  4

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
        A   B   C   D
    0   0.0 2.0 0.0 0
    1   3.0 4.0 0.0 1
    2   0.0 0.0 0.0 5
    3   0.0 3.0 0.0 4

    We can also propagate non-null values forward or backward.

    >>> df.fillna(method='ffill')
        A   B   C   D
    0   NaN 2.0 NaN 0
    1   3.0 4.0 NaN 1
    2   3.0 4.0 NaN 5
    3   3.0 3.0 NaN 4

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}
    >>> df.fillna(value=values)
        A   B   C   D
    0   0.0 2.0 2.0 0
    1   3.0 4.0 2.0 1
    2   0.0 1.0 2.0 5
    3   0.0 3.0 2.0 4

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
        A   B   C   D
    0   0.0 2.0 2.0 0
    1   3.0 4.0 NaN 1
    2   NaN 1.0 NaN 5
    3   NaN 3.0 NaN 4

In [6]:
import unidecode
def quitar_caracteres(entrada):
    return str.lower(unidecode.unidecode(entrada))

In [7]:
billtex=bill.iloc[:, [0,1,3]]
billtex.head()

       artist.inverted                                  track genre
0      Destiny's Child               Independent Women Part I  Rock
1              Santana                           Maria, Maria  Rock
2        Savage Garden                     I Knew I Loved You  Rock
3              Madonna                                  Music  Rock
4  Aguilera, Christina  Come On Over Baby (All I Want Is You)  Rock

In [8]:
billtex.applymap(quitar_caracteres)

,artist.inverted,track,genre
0,destiny's child,independent women part i,rock
1,santana,"maria, maria",rock
2,savage garden,i knew i loved you,rock
3,madonna,music,rock
4,"aguilera, christina",come on over baby (all i want is you),rock
5,janet,doesn't really matter,rock
6,destiny's child,say my name,rock
7,"iglesias, enrique",be with you,latin
8,sisqo,incomplete,rock
9,lonestar,amazed,country
10,n'sync,it's gonna be me,rock
11,"aguilera, christina",what a girl wants,rock
12,vertical horizon,everything you want,rock
13,creed,with arms wide open,rock
14,aaliyah,try again,rock
15,matchbox twenty,bent,rock
16,"carey, mariah",thank god i found you,rock
17,"hill, faith",breathe,rap
18,mya,case of the ex (whatcha gonna do),rock
19,dream,he loves u not,rock
20,"braxton, toni",he wasn't man enough,rock
21,"anthony, marc",you sang to me,latin
22,98!,give me just one night (una noche),rock
23,destiny's child,jumpin' jumpin',rock
24,3 doors down,kryptonite,rock
25,sisqo,thong song,rock
26,"aguilera, christina",i turn to you,rock
27,"houston, whitney",my love is your love,rock
28,joe,i wanna know,rock
29,"jordan, montell",get it on.. tonite,rap
...,...,...,...
287,2ge+her,the hardest part of breaking up (is getting ba...,r&b
288,madison avenue,don't call me baby,electronica
289,eve,got it all,rap
290,limp bizkit,re-arranged,rock
291,"spencer, tracie",still in my heart,rock
292,nu flavor,3 little words,r&b
293,tamar,if you don't wanna love me,rock
294,"levert, gerald",baby u are,r&b
295,"hart, beth",l.a. song,country
296,"diffie, joe",the quittin' kind,country
297,funkmaster flex,do you,rap
298,"price, kelly",love sets you free,rock
299,en vogue,riddle,rock
300,"herndon, ty",no mercy,country
301,anastacia,i'm outta love,pop
302,trina,pull over,rap
303,lil' mo,ta da,rap
304,a*teens,dancing queen,pop
305,"sheist, shade",where i wanna be,rap
306,de la soul,all good?,rap
307,"larrieux, amel",get up,r&b
308,"braxton, toni",spanish guitar,rock
309,tuesday,i know,rock
310,ll cool j,imagine that,rap
311,master p,souljas,rap
312,ghostface killah,cherchez laghost,r&b
313,"smith, will",freakin' it,rap
314,zombie nation,kernkraft 400,rock
315,"eastsidaz, the",got beef,rap
316,fragma,toca's miracle,r&b

In [9]:
bill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 82 columns):
artist.inverted    317 non-null object
track              317 non-null object
time               317 non-null object
genre              317 non-null object
date.entered       317 non-null datetime64[ns]
date.peaked        317 non-null datetime64[ns]
x1st.week          317 non-null int64
x2nd.week          312 non-null float64
x3rd.week          307 non-null float64
x4th.week          300 non-null float64
x5th.week          292 non-null float64
x6th.week          280 non-null float64
x7th.week          269 non-null float64
x8th.week          260 non-null float64
x9th.week          253 non-null float64
x10th.week         244 non-null float64
x11th.week         236 non-null float64
x12th.week         222 non-null float64
x13th.week         210 non-null float64
x14th.week         204 non-null float64
x15th.week         197 non-null float64
x16th.week         182 non-null float64
x17th.week         177 non-null float64
x18th.week         166 non-null float64
x19th.week         156 non-null float64
x20th.week         146 non-null float64
x21st.week         65 non-null float64
x22nd.week         55 non-null float64
x23rd.week         48 non-null float64
x24th.week         46 non-null float64
x25th.week         38 non-null float64
x26th.week         36 non-null float64
x27th.week         29 non-null float64
x28th.week         24 non-null float64
x29th.week         20 non-null float64
x30th.week         20 non-null float64
x31st.week         19 non-null float64
x32nd.week         18 non-null float64
x33rd.week         12 non-null float64
x34th.week         10 non-null float64
x35th.week         9 non-null float64
x36th.week         9 non-null float64
x37th.week         9 non-null float64
x38th.week         8 non-null float64
x39th.week         8 non-null float64
x40th.week         7 non-null float64
x41st.week         7 non-null float64
x42nd.week         6 non-null float64
x43rd.week         6 non-null float64
x44th.week         6 non-null float64
x45th.week         5 non-null float64
x46th.week         5 non-null float64
x47th.week         5 non-null float64
x48th.week         4 non-null float64
x49th.week         4 non-null float64
x50th.week         4 non-null float64
x51st.week         4 non-null float64
x52nd.week         4 non-null float64
x53rd.week         4 non-null float64
x54th.week         2 non-null float64
x55th.week         2 non-null float64
x56th.week         2 non-null float64
x57th.week         2 non-null float64
x58th.week         2 non-null float64
x59th.week         2 non-null float64
x60th.week         2 non-null float64
x61st.week         2 non-null float64
x62nd.week         2 non-null float64
x63rd.week         2 non-null float64
x64th.week         2 non-null float64
x65th.week         1 non-null float64
x66th.week         0 non-null float64
x67th.week         0 non-null float64
x68th.week         0 non-null float64
x69th.week         0 non-null float64
x70th.week         0 non-null float64
x71st.week         0 non-null float64
x72nd.week         0 non-null float64
x73rd.week         0 non-null float64
x74th.week         0 non-null float64
x75th.week         0 non-null float64
x76th.week         0 non-null float64
dtypes: datetime64[ns](2), float64(75), int64(1), object(4)
memory usage: 203.2+ KB

In [10]:
billfec=bill.iloc[:,[4,5]]

In [11]:
bill.iloc[:,[4,5]]

    date.entered date.peaked
0     2000-09-23  2000-11-18
1     2000-02-12  2000-04-08
2     1999-10-23  2000-01-29
3     2000-08-12  2000-09-16
4     2000-08-05  2000-10-14
5     2000-06-17  2000-08-26
6     1999-12-25  2000-03-18
7     2000-04-01  2000-06-24
8     2000-06-24  2000-08-12
9     1999-06-05  2000-03-04
10    2000-05-06  2000-07-29
11    1999-11-27  2000-01-15
12    2000-01-22  2000-07-15
13    2000-05-13  2000-11-11
14    2000-03-18  2000-06-17
15    2000-04-29  2000-07-22
16    1999-12-11  2000-02-19
17    1999-11-06  2000-04-22
18    2000-08-19  2000-12-02
19    2000-09-30  2000-12-30
20    2000-03-18  2000-05-06
21    2000-02-26  2000-06-03
22    2000-08-19  2000-09-30
23    2000-05-13  2000-08-19
24    2000-04-08  2000-11-11
25    2000-01-29  2000-05-20
26    2000-04-15  2000-07-01
27    1999-09-04  2000-01-08
28    2000-01-01  2000-07-01
29    1999-10-23  2000-02-12
..           ...         ...
287   2000-09-02  2000-09-09
288   2000-07-08  2000-09-16
289   2000-07-15  2000-07-22
290   1999-12-04  2000-02-05
291   2000-03-04  2000-03-11
292   2000-06-03  2000-06-17
293   2000-03-25  2000-04-15
294   2000-08-19  2000-08-26
295   1999-11-27  2000-01-15
296   2000-01-01  2000-01-22
297   2000-11-11  2000-12-02
298   2000-05-13  2000-05-20
299   2000-06-17  2000-06-17
300   2000-03-18  2000-05-06
301   2000-04-01  2000-04-01
302   2000-09-09  2000-09-16
303   2000-08-12  2000-09-16
304   2000-07-08  2000-07-29
305   2000-11-11  2000-11-18
306   2000-12-23  2000-12-23
307   2000-03-04  2000-03-11
308   2000-12-02  2000-12-02
309   2000-12-30  2000-12-30
310   2000-08-12  2000-08-19
311   2000-11-18  2000-11-18
312   2000-08-05  2000-08-05
313   2000-02-12  2000-02-12
314   2000-09-02  2000-09-02
315   2000-07-01  2000-07-01
316   2000-10-28  2000-10-28

[317 rows x 2 columns]

In [12]:
type(bill.iloc[:,[4,5]])

pandas.core.frame.DataFrame

In [13]:
help(pd.to_datetime)

Help on function to_datetime in module pandas.core.tools.datetimes:

to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=None, box=True, format=None, exact=True, unit=None, infer_datetime_format=False, origin='unix')
    Convert argument to datetime.

    Parameters
    ----------
    arg : integer, float, string, datetime, list, tuple, 1-d array, Series

        .. versionadded: 0.18.1

           or DataFrame/dict-like

    errors : {'ignore', 'raise', 'coerce'}, default 'raise'

        - If 'raise', then invalid parsing will raise an exception
        - If 'coerce', then invalid parsing will be set as NaT
        - If 'ignore', then invalid parsing will return the input
    dayfirst : boolean, default False
        Specify a date parse order if `arg` is str or its list-likes.
        If True, parses dates with the day first, eg 10/11/12 is parsed as
        2012-11-10.
        Warning: dayfirst=True is not strict, but will prefer to parse
        with day first (this is a known bug, based on dateutil behavior).
    yearfirst : boolean, default False
        Specify a date parse order if `arg` is str or its list-likes.

        - If True parses dates with the year first, eg 10/11/12 is parsed as
          2010-11-12.
        - If both dayfirst and yearfirst are True, yearfirst is preceded (same
          as dateutil).

        Warning: yearfirst=True is not strict, but will prefer to parse
        with year first (this is a known bug, based on dateutil beahavior).

        .. versionadded: 0.16.1

    utc : boolean, default None
        Return UTC DatetimeIndex if True (converting any tz-aware
        datetime.datetime objects as well).
    box : boolean, default True

        - If True returns a DatetimeIndex
        - If False returns ndarray of values.
    format : string, default None
        strftime to parse time, eg "%d/%m/%Y", note that "%f" will parse
        all the way up to nanoseconds.
    exact : boolean, True by default

        - If True, require an exact format match.
        - If False, allow the format to match anywhere in the target string.

    unit : string, default 'ns'
        unit of the arg (D,s,ms,us,ns) denote the unit, which is an
        integer or float number. This will be based off the origin.
        Example, with unit='ms' and origin='unix' (the default), this
        would calculate the number of milliseconds to the unix epoch start.
    infer_datetime_format : boolean, default False
        If True and no `format` is given, attempt to infer the format of the
        datetime strings, and if it can be inferred, switch to a faster
        method of parsing them. In some cases this can increase the parsing
        speed by ~5-10x.
    origin : scalar, default is 'unix'
        Define the reference date. The numeric values would be parsed as number
        of units (defined by `unit`) since this reference date.

        - If 'unix' (or POSIX) time; origin is set to 1970-01-01.
        - If 'julian', unit must be 'D', and origin is set to beginning of
          Julian Calendar. Julian day number 0 is assigned to the day starting
          at noon on January 1, 4713 BC.
        - If Timestamp convertible, origin is set to Timestamp identified by
          origin.

        .. versionadded: 0.20.0

    Returns
    -------
    ret : datetime if parsing succeeded.
        Return type depends on input:

        - list-like: DatetimeIndex
        - Series: Series of datetime64 dtype
        - scalar: Timestamp

        In case when it is not possible to return designated types (e.g. when
        any element of input is before Timestamp.min or after Timestamp.max)
        return will have datetime.datetime type (or correspoding array/Series).

    Examples
    --------

    Assembling a datetime from multiple columns of a DataFrame. The keys can be
    common abbreviations like ['year', 'month', 'day', 'minute', 'second',
    'ms', 'us', 'ns']) or plurals of the same

    >>> df = pd.DataFrame({'year': [2015, 2016],
                           'month': [2, 3],
                           'day': [4, 5]})
    >>> pd.to_datetime(df)
    0   2015-02-04
    1   2016-03-05
    dtype: datetime64[ns]

    If a date does not meet the `timestamp limitations
    <http://pandas.pydata.org/pandas-docs/stable/timeseries.html
    #timeseries-timestamp-limits>`_, passing errors='ignore'
    will return the original input instead of raising any exception.

    Passing errors='coerce' will force an out-of-bounds date to NaT,
    in addition to forcing non-dates (or non-parseable dates) to NaT.

    >>> pd.to_datetime('13000101', format='%Y%m%d', errors='ignore')
    datetime.datetime(1300, 1, 1, 0, 0)
    >>> pd.to_datetime('13000101', format='%Y%m%d', errors='coerce')
    NaT

    Passing infer_datetime_format=True can often-times speedup a parsing
    if its not an ISO8601 format exactly, but in a regular format.

    >>> s = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000']*1000)

    >>> s.head()
    0    3/11/2000
    1    3/12/2000
    2    3/13/2000
    3    3/11/2000
    4    3/12/2000
    dtype: object

    >>> %timeit pd.to_datetime(s,infer_datetime_format=True)
    100 loops, best of 3: 10.4 ms per loop

    >>> %timeit pd.to_datetime(s,infer_datetime_format=False)
    1 loop, best of 3: 471 ms per loop

    Using a unix epoch time

    >>> pd.to_datetime(1490195805, unit='s')
    Timestamp('2017-03-22 15:16:45')
    >>> pd.to_datetime(1490195805433502912, unit='ns')
    Timestamp('2017-03-22 15:16:45.433502912')

    .. warning:: For float arg, precision rounding might happen. To prevent
        unexpected behavior use a fixed-width exact type.

    Using a non-unix epoch origin

    >>> pd.to_datetime([1, 2, 3], unit='D',
                       origin=pd.Timestamp('1960-01-01'))
    0    1960-01-02
    1    1960-01-03
    2    1960-01-04

    See also
    --------
    pandas.DataFrame.astype : Cast argument to a specified dtype.
    pandas.to_timedelta : Convert argument to timedelta.

In [14]:
genre_gr=bill.groupby('genre')

In [15]:
genre_gr.head(8)

,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,81,54.0,44.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Hill, Faith",Breathe,4:04,Rap,1999-11-06,2000-04-22,81,68.0,62.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"Anthony, Marc",You Sang To Me,3:50,Latin,2000-02-26,2000-06-03,77,54.0,50.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Jordan, Montell",Get It On.. Tonite,4:34,Rap,1999-10-23,2000-02-12,92,80.0,72.0,69.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Eminem,The Real Slim Shady,4:42,Rap,2000-05-06,2000-06-24,70,32.0,20.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Blaque,Bring It All To Me,3:46,Pop,1999-10-23,2000-01-22,73,63.0,50.0,42.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,"Elliott, Missy ""Misdemeanor""",Hot Boyz,3:51,Rap,1999-11-27,2000-01-08,36,21.0,13.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Eiffel 65,Blue (Da Ba Dee),3:29,Electronica,1999-12-11,2000-01-29,67,29.0,16.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Nelly,(Hot S**t) Country Grammar,4:17,Rap,2000-04-29,2000-09-16,100,99.0,96.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Kenny G,Auld Lang Syne (The Millenium Mix),7:50,Jazz,1999-12-25,2000-01-08,89,89.0,7.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Ja Rule,Between Me And You,4:05,Rap,2000-09-16,2000-11-18,85,74.0,61.0,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,"Rimes, LeAnn",I Need You,3:42,Country,2000-05-27,2000-08-12,77,68.0,67.0,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,Jay-Z,I Just Wanna Love U (Give It 2 Me),3:50,Rap,2000-10-28,2000-12-30,58,45.0,35.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,"Martin, Ricky",She Bangs,4:02,Latin,2000-10-07,2000-12-02,38,28.0,21.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Mystikal,Shake Ya Ass,4:46,Rap,2000-08-12,2000-10-28,97,90.0,65.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Profyle,Liar,3:57,R&B,2000-09-16,2000-10-28,52,32.0,25.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,"Dixie Chicks, The",Goodbye Earl,4:19,Country,2000-03-18,2000-05-06,40,29.0,24.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Guy,Dancin',4:08,R&B,1999-12-18,2000-01-01,46,29.0,19.0,22.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Hanson,This Time Around,4:14,Country,2000-04-22,2000-05-06,22,22.0,20.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,"Simpson, Jessica",I Think I'm In Love With You,3:32,Pop,2000-07-01,2000-08-12,63,52.0,44.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,M2M,Don't Say You Love Me,3:41,Pop,1999-11-20,2000-01-08,72,53.0,62.0,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,"Brock, Chad",Yes!,3:22,Country,2000-04-08,2000-07-01,90,77.0,66.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,"Martin, Ricky",Shake Your Bon-Bon,3:08,Latin,1999-11-20,2000-02-12,74,66.0,52.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,"Rimes, LeAnn",Big Deal,3:03,Country,1999-10-16,2000-01-01,71,52.0,51.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,"Moore, Mandy",I Wanna Be With You,4:12,Pop,2000-06-17,2000-08-12,69,63.0,54.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,D'Angelo,Untitled (How Does It Feel),7:10,R&B,2000-01-22,2000-02-19,77,56.0,35.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,"Messina, Jo Dee",That's The Way,3:17,Country,2000-06-24,2000-08-26,78,67.0,63.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Son By Four,A Puro Dolor (Purest Of Pain),3:30,Latin,2000-04-08,2000-08-19,80,80.0,80.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,"Dixie Chicks, The",Cowboy Take Me Away,4:51,Country,1999-11-27,2000-01-29,79,72.0,70.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Alice Deejay,Better Off Alone,6:50,Electronica,2000-04-08,2000-06-03,79,65.0,53.0,48.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,Hoku,Another Dumb Blonde,3:47,Pop,2000-02-19,2000-04-08,69,49.0,49.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,"Iglesias, Enrique",Rhythm Divine,7:35,Latin,1999-12-04,2000-01-22,90,84.0,79.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,"Fabian, Lara",I Will Love Again,3:43,Pop,2000-06-10,2000-08-12,91,80.0,75.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,J-Shin,One Night Stand,4:34,R&B,1999-12-25,2000-02-26,96,96.0,69.0,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,"Carter, Aaron",Aaron's Party (Come Get It),3:23,R&B,2000-08-26,2000-09-16,99,75.0,57.0,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,Lucy Pearl,Dance Tonight,3:45,R&B,2000-05-20,2000-07-29,80,75.0,63.0,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,Baha Men,Who Let The Dogs Out,3:17,R&B,2000-07-22,2000-10-21,99,92.0,85.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,Ideal,Whatever,3:48,R&B,2000-06-10,2000-08-19,75,75.0,67.0,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,"Lopez, Jennifer",Feelin' Good,4:28,Latin,2000-02-19,2000-04-08,79,79.0,66.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,Beenie Man,Girls Dem Sugar,4:17,Reggae,2000-10-21,2000-12-02,72,72.0,63.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,"Adams, Yolanda",Open My Heart,5:30,Gospel,2000-08-26,2000-10-21,76,76.0,74.0,69.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,M2M,Mirror Mirror,3:19,Pop,2000-04-01,2000-05-27,87,87.0,94.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,"Martin, Ricky",Private Emotion,4:02,Latin,2000-03-11,2000-03-18,76,67.0,71.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,Fatboy Slim,The Rockafeller Skank,4:00,Electronica,1999-11-13,2000-01-22,94,94.0,94.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
288,Madison Avenue,Don't Call Me Baby,3:44,Electronica,2000-07-08,2000-09-16,98,96.0,93.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,Anastacia,I'm Outta Love,4:01,Pop,2000-04-01,2000-04-01,92,NaN,NaN,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
genre_gr.get_group('Rock')

,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,59,52.0,43.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,83,83.0,44.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,77,66.0,61.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,N'Sync,It's Gonna Be Me,3:10,Rock,2000-05-06,2000-07-29,82,70.0,51.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Aguilera, Christina",What A Girl Wants,3:18,Rock,1999-11-27,2000-01-15,71,51.0,28.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Vertical Horizon,Everything You Want,4:01,Rock,2000-01-22,2000-07-15,70,61.0,53.0,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Creed,With Arms Wide Open,3:52,Rock,2000-05-13,2000-11-11,84,78.0,76.0,74.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Aaliyah,Try Again,4:03,Rock,2000-03-18,2000-06-17,59,53.0,38.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,matchbox twenty,Bent,4:12,Rock,2000-04-29,2000-07-22,60,37.0,29.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"Carey, Mariah",Thank God I Found You,4:14,Rock,1999-12-11,2000-02-19,82,68.0,50.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Mya,Case Of The Ex (Whatcha Gonna Do),3:50,Rock,2000-08-19,2000-12-02,72,57.0,52.0,47.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Dream,He Loves U Not,3:43,Rock,2000-09-30,2000-12-30,99,92.0,81.0,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"Braxton, Toni",He Wasn't Man Enough,4:21,Rock,2000-03-18,2000-05-06,63,55.0,48.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,98Â¡,Give Me Just One Night (Una Noche),3:24,Rock,2000-08-19,2000-09-30,51,39.0,34.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Destiny's Child,Jumpin' Jumpin',3:48,Rock,2000-05-13,2000-08-19,74,71.0,65.0,62.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,3 Doors Down,Kryptonite,3:53,Rock,2000-04-08,2000-11-11,81,70.0,68.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Sisqo,Thong Song,4:05,Rock,2000-01-29,2000-05-20,74,63.0,35.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"Aguilera, Christina",I Turn To You,4:00,Rock,2000-04-15,2000-07-01,50,39.0,30.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"Houston, Whitney",My Love Is Your Love,4:16,Rock,1999-09-04,2000-01-08,81,68.0,44.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Joe,I Wanna Know,4:57,Rock,2000-01-01,2000-07-01,94,86.0,69.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,N'Sync,Bye Bye Bye,3:15,Rock,2000-01-29,2000-04-15,42,20.0,19.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Pink,Most Girls,4:06,Rock,2000-08-12,2000-11-25,85,70.0,52.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,"Mumba, Samantha",Gotta Tell You,3:19,Rock,2000-09-09,2000-12-09,85,72.0,65.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"Gray, Macy",I Try,3:52,Rock,2000-02-19,2000-05-20,68,51.0,47.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,N'Sync,This I Promise You,4:23,Rock,2000-09-30,2000-12-02,68,31.0,19.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Red Hot Chili Peppers,Californication,5:21,Rock,2000-07-29,2000-10-14,72,72.0,72.0,77.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Third Eye Blind,Deep Inside Of You,4:10,Rock,2000-09-02,2000-10-07,80,73.0,70.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,"Offspring, The",Original Prankster,3:42,Rock,2000-11-25,2000-12-09,74,71.0,70.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,"Houston, Whitney","Same Script, Different Cast",4:45,Rock,2000-06-17,2000-07-15,71,71.0,71.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,"Kravitz, Lenny",I Belong To You,4:17,Rock,2000-03-25,2000-04-08,78,77.0,71.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,Q-Tip,Breathe And Stop,4:06,Rock,2000-01-22,2000-01-22,71,71.0,81.0,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,"Wallflowers, The",Sleepwalker,3:29,Rock,2000-10-28,2000-10-28,73,73.0,74.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,Limp Bizkit,N 2 Gether Now,3:55,Rock,1999-12-04,2000-01-08,94,88.0,85.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,Metallica,No Leaf Clover (Live),5:43,Rock,2000-02-12,2000-03-11,86,81.0,78.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,"Bega, Lou",Tricky Tricky,3:23,Rock,2000-01-29,2000-02-05,75,74.0,87.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Metallica,I Disappear,4:26,Rock,2000-05-13,2000-06-17,86,84.0,88.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,"McKnight, Brian",Stay Or Let It Go,4:32,Rock,2000-02-26,2000-03-25,95,92.0,82.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,Ginuwine,The Best Man I Can Be,4:06,Rock,2000-01-08,2000-03-04,97,97.0,83.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,Before Dark,Monica,4:04,Rock,2000-05-20,2000-06-17,95,87.0,80.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,"Estefan, Gloria",No Me Dejes De Querer,3:25,Rock,2000-06-10,2000-06-10,77,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,Stone Temple Pilots,Sour Girl,4:16,Rock,2000-07-08,2000-07-29,79,79.0,79.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,"Thomas, Carl",Summer Rain,4:57,Rock,2000-09-23,2000-10-14,82,82.0,86.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,"Moore, Chante",Straight Up,3:40,Rock,2000-10-28,2000-12-02,98,98.0,97.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,"Hollister, Dave",Can't Stay,6:17,Rock,2000-03-25,2000-03-25,84,84.0,93.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,Tamia,Can't Go For That,3:38,Rock,2000-09-16,2000-09-30,90,86.0,84.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,LFO,West Side Story,3:27,Rock,2000-08-05,2000-08-12,96,84.0,88.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,"Carter, Torrey",Take That,3:43,Rock,2000-06-24,2000-07-08,94,88.0,86.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,Limp Bizkit,Re-Arranged,4:08,Rock,1999-12-04,2000-02-05,91,91.0,90.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,"Spencer, Tracie",Still In My Heart,4:11,Rock,2000-03-04,2000-03-11,95,88.0,98.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Tamar,If You Don't Wanna Love Me,4:02,Rock,2000-03-25,2000-04-15,98,98.0,92.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,"Price, Kelly",Love Sets You Free,3:46,Rock,2000-05-13,2000-05-20,92,91.0,98.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,En Vogue,Riddle,5:10,Rock,2000-06-17,2000-06-17,92,92.0,97.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,"Braxton, Toni",Spanish Guitar,4:24,Rock,2000-12-02,2000-12-02,98,98.0,98.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
309,Tuesday,I Know,4:06,Rock,2000-12-30,2000-12-30,98,98.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
genre_gr.get_group('Latin')

,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
7,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,63,45.0,34.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"Anthony, Marc",You Sang To Me,3:50,Latin,2000-02-26,2000-06-03,77,54.0,50.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,"Martin, Ricky",She Bangs,4:02,Latin,2000-10-07,2000-12-02,38,28.0,21.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,"Martin, Ricky",Shake Your Bon-Bon,3:08,Latin,1999-11-20,2000-02-12,74,66.0,52.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Son By Four,A Puro Dolor (Purest Of Pain),3:30,Latin,2000-04-08,2000-08-19,80,80.0,80.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,"Iglesias, Enrique",Rhythm Divine,7:35,Latin,1999-12-04,2000-01-22,90,84.0,79.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,"Lopez, Jennifer",Feelin' Good,4:28,Latin,2000-02-19,2000-04-08,79,79.0,66.0,54.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,"Martin, Ricky",Private Emotion,4:02,Latin,2000-03-11,2000-03-18,76,67.0,71.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,"Anthony, Marc",My Baby You,3:59,Latin,2000-09-16,2000-10-07,82,76.0,76.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#periodo_t=bill.iloc[:,[5]]- bill.iloc[:,[4]]

In [63]:
bill['Periodo_time'] = (bill['date.peaked'] - bill['date.entered']).dt.days

In [64]:
bill.head()

,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,...,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week,Periodo_time
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70

In [21]:
#type(bill['date.peaked'])
type(bill['date.entered'])

pandas.core.series.Series

In [22]:
#from datetime import datetime

In [65]:
def change_column_order(df, col_name, index):
    cols = df.columns.tolist()
    cols.remove(col_name)
    cols.insert(index, col_name)
    
    return df[cols]

In [66]:
df = change_column_order(bill,'Periodo_time', 6)

In [67]:
#Mejor ranking alcanzado
df['mejor_rank'] = df.iloc[:,7:].min(axis=1)

C:\Users\helen\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [76]:
#total rank por  track
#df.iloc[:,7:].sum(skipna = True)
df['total_rank_tr'] =df.iloc[:,7:].sum(axis = 'columns')

C:\Users\helen\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [81]:
df = change_column_order(df,'mejor_rank', 7)

In [82]:
df = change_column_order(df,'total_rank_tr', 8)

In [83]:
df.head(12)

,artist.inverted,track,time,genre,date.entered,date.peaked,Periodo_time,mejor_rank,total_rank_tr,x1st.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,56,1.0,416.0,78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,56,1.0,274.0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,98,1.0,574.0,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,35,1.0,324.0,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,70,1.0,420.0,57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Janet,Doesn't Really Matter,4:17,Rock,2000-06-17,2000-08-26,70,1.0,467.0,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Destiny's Child,Say My Name,4:31,Rock,1999-12-25,2000-03-18,84,1.0,669.0,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"Iglesias, Enrique",Be With You,3:36,Latin,2000-04-01,2000-06-24,84,1.0,318.0,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sisqo,Incomplete,3:52,Rock,2000-06-24,2000-08-12,49,1.0,633.0,77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,273,1.0,1471.0,81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,N'Sync,It's Gonna Be Me,3:10,Rock,2000-05-06,2000-07-29,84,1.0,543.0,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Aguilera, Christina",What A Girl Wants,3:18,Rock,1999-11-27,2000-01-15,49,1.0,464.0,71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
help(pd.melt)

Help on function melt in module pandas.core.reshape.reshape:

melt(frame, id_vars=None, value_vars=None, var_name=None, value_name='value', col_level=None)
    "Unpivots" a DataFrame from wide format to long format, optionally
    leaving identifier variables set.

    This function is useful to massage a DataFrame into a format where one
    or more columns are identifier variables (`id_vars`), while all other
    columns, considered measured variables (`value_vars`), are "unpivoted" to
    the row axis, leaving just two non-identifier columns, 'variable' and
    'value'.


    Parameters
    ----------
    frame : DataFrame
    id_vars : tuple, list, or ndarray, optional
        Column(s) to use as identifier variables.
    value_vars : tuple, list, or ndarray, optional
        Column(s) to unpivot. If not specified, uses all columns that
        are not set as `id_vars`.
    var_name : scalar
        Name to use for the 'variable' column. If None it uses
        ``frame.columns.name`` or 'variable'.
    value_name : scalar, default 'value'
        Name to use for the 'value' column.
    col_level : int or string, optional
        If columns are a MultiIndex then use this level to melt.

    See also
    --------
    DataFrame.melt
    pivot_table
    DataFrame.pivot

    Examples
    --------
    >>> import pandas as pd
    >>> df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
    ...                    'B': {0: 1, 1: 3, 2: 5},
    ...                    'C': {0: 2, 1: 4, 2: 6}})
    >>> df
       A  B  C
    0  a  1  2
    1  b  3  4
    2  c  5  6

    >>> pd.melt(df, id_vars=['A'], value_vars=['B'])
       A variable  value
    0  a        B      1
    1  b        B      3
    2  c        B      5

    >>> pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])
       A variable  value
    0  a        B      1
    1  b        B      3
    2  c        B      5
    3  a        C      2
    4  b        C      4
    5  c        C      6

    The names of 'variable' and 'value' columns can be customized:

    >>> pd.melt(df, id_vars=['A'], value_vars=['B'],
    ...         var_name='myVarname', value_name='myValname')
       A myVarname  myValname
    0  a         B          1
    1  b         B          3
    2  c         B          5

    If you have multi-index columns:

    >>> df.columns = [list('ABC'), list('DEF')]
    >>> df
       A  B  C
       D  E  F
    0  a  1  2
    1  b  3  4
    2  c  5  6

    >>> pd.melt(df, col_level=0, id_vars=['A'], value_vars=['B'])
       A variable  value
    0  a        B      1
    1  b        B      3
    2  c        B      5

    >>> pd.melt(df, id_vars=[('A', 'D')], value_vars=[('B', 'E')])
      (A, D) variable_0 variable_1  value
    0      a          B          E      1
    1      b          B          E      3
    2      c          B          E      5

In [29]:
id_vars = ["artist.inverted", "track", "time", "genre",  "date.entered", "date.peaked","Periodo_time"]

In [30]:
bill_tidy = pd.melt(frame=df,id_vars=id_vars, var_name="week", value_name="rank")

In [31]:
bill_tidy.head()

,artist.inverted,track,time,genre,date.entered,date.peaked,Periodo_time,week,rank
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,56,mejor_rank,1.0
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,56,mejor_rank,1.0
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,98,mejor_rank,1.0
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,35,mejor_rank,1.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,70,mejor_rank,1.0

In [32]:
def periodo_en_semanas(x):
    semanas = x/7
    return semanas

In [33]:
bill_tidy["Periodo_time"] = bill_tidy["Periodo_time"].apply(periodo_en_semanas)
bill_tidy.head()

,artist.inverted,track,time,genre,date.entered,date.peaked,Periodo_time,week,rank
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,8.0,mejor_rank,1.0
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,8.0,mejor_rank,1.0
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,14.0,mejor_rank,1.0
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,5.0,mejor_rank,1.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,10.0,mejor_rank,1.0

In [34]:

# Formatting 
bill_tidy["week"] = bill_tidy["week"].str.extract('(\d+)', expand=False).astype(float)

In [35]:
bill_tidy["rank"] = bill_tidy["rank"].astype(float)

In [36]:
bill_f = bill_tidy.dropna()

In [37]:
bill_f['date'] = pd.to_datetime(bill_f['date.entered']) + pd.to_timedelta(bill_f['week'], unit='w') - pd.DateOffset(weeks=1)

C:\Users\helen\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [38]:
bill_f = bill_f[[  "artist.inverted",  "track",  "time",  "genre", "week",  "rank", "date"]]
df = bill_f.sort_values(ascending=True, by=["artist.inverted","track","week","rank"])

# Assigning the tidy dataset to a variable for future usage
billboard = df

In [39]:

df.head(20)

,artist.inverted,track,time,genre,week,rank,date
563,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,1.0,87.0,2000-02-26
880,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,2.0,82.0,2000-03-04
1197,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,3.0,72.0,2000-03-11
1514,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,4.0,77.0,2000-03-18
1831,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,5.0,87.0,2000-03-25
2148,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,6.0,94.0,2000-04-01
2465,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,7.0,99.0,2000-04-08
604,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,1.0,91.0,2000-09-02
921,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,2.0,87.0,2000-09-09
1238,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,3.0,92.0,2000-09-16
341,3 Doors Down,Kryptonite,3:53,Rock,1.0,81.0,2000-04-08
658,3 Doors Down,Kryptonite,3:53,Rock,2.0,70.0,2000-04-15
975,3 Doors Down,Kryptonite,3:53,Rock,3.0,68.0,2000-04-22
1292,3 Doors Down,Kryptonite,3:53,Rock,4.0,67.0,2000-04-29
1609,3 Doors Down,Kryptonite,3:53,Rock,5.0,66.0,2000-05-06
1926,3 Doors Down,Kryptonite,3:53,Rock,6.0,57.0,2000-05-13
2243,3 Doors Down,Kryptonite,3:53,Rock,7.0,54.0,2000-05-20
2560,3 Doors Down,Kryptonite,3:53,Rock,8.0,53.0,2000-05-27
2877,3 Doors Down,Kryptonite,3:53,Rock,9.0,51.0,2000-06-03
3194,3 Doors Down,Kryptonite,3:53,Rock,10.0,51.0,2000-06-10

In [40]:
df.shape

(5307, 7)

In [41]:
bill.shape

(317, 83)

In [42]:
songs_cols = ["artist.inverted", "track", "time", "genre"]
songs = billboard[songs_cols].drop_duplicates()
songs = songs.reset_index(drop=True)
songs["song_id"] = songs.index
songs.head(10)

,artist.inverted,track,time,genre,song_id
0,2 Pac,Baby Don't Cry (Keep Ya Head Up II),4:22,Rap,0
1,2Ge+her,The Hardest Part Of Breaking Up (Is Getting Ba...,3:15,R&B,1
2,3 Doors Down,Kryptonite,3:53,Rock,2
3,3 Doors Down,Loser,4:24,Rock,3
4,504 Boyz,Wobble Wobble,3:35,Rap,4
5,98Â¡,Give Me Just One Night (Una Noche),3:24,Rock,5
6,A*Teens,Dancing Queen,3:44,Pop,6
7,Aaliyah,I Don't Wanna,4:15,Rock,7
8,Aaliyah,Try Again,4:03,Rock,8
9,"Adams, Yolanda",Open My Heart,5:30,Gospel,9

In [43]:
ranks = pd.merge(billboard, songs, on=["artist.inverted", "track", "time", "genre"])
ranks = ranks[["song_id", "date","rank"]]
ranks.head(10)

   song_id       date  rank
0        0 2000-02-26  87.0
1        0 2000-03-04  82.0
2        0 2000-03-11  72.0
3        0 2000-03-18  77.0
4        0 2000-03-25  87.0
5        0 2000-04-01  94.0
6        0 2000-04-08  99.0
7        1 2000-09-02  91.0
8        1 2000-09-09  87.0
9        1 2000-09-16  92.0

In [44]:
genre_ro=bill_tidy.groupby('genre')
grock=genre_ro.get_group('Rock')

In [45]:
grock.head()

,artist.inverted,track,time,genre,date.entered,date.peaked,Periodo_time,week,rank
0,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,8.0,NaN,1.0
1,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,8.0,NaN,1.0
2,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,14.0,NaN,1.0
3,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,5.0,NaN,1.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,10.0,NaN,1.0

In [46]:
#contar los valores missing en cada columna
missing_values_count =grock.isnull().sum()

In [47]:
#Contamos el total de datos
total_cells_rock = np.product(grock.shape)

In [48]:
#Contamos el total de valores missing
total_missing_rock = missing_values_count.sum()

In [49]:
(total_missing_rock/total_cells_rock)*100

8.386260941005466

In [50]:
#Elimino las filas missing
rock_n=grock.dropna()

In [51]:
rock_n.isnull().sum()

artist.inverted    0
track              0
time               0
genre              0
date.entered       0
date.peaked        0
Periodo_time       0
week               0
rank               0
dtype: int64

In [52]:
graf_rock=rock_n.iloc[:,8]
graf1 = graf_rock.plot()
plt.xlabel("rank")
plt.ylabel("week")
#plt.grid(True)
%matplotlib inline
plt.figure()
#plt.show(graf1)

graf1.plot(figsize=(16,8))

[]